class EMG:
    channel_one=[]
    channel_two=[]
    channel_three=[]
    channel_four=[]
    channel_five=[]
    channel_six=[]
    channel_seven=[]
    channel_eight=[]
    channel_nine=[]
    channel_ten=[]
    channel_eleven=[]
    channel_twelve=[]
    channel_thirteen=[]
    channel_fourteen=[]
    channel_fifteen=[]
    channel_sixteen=[]
    all_channel_data=[]
    time=[]

    def update_emg_data(self,data,time):
        self.all_channel_data.append(data)
        self.channel_one.append(data[0])
        self.channel_two.append(data[1])
        self.channel_three.append(data[2])
        self.channel_four.append(data[3])
        self.channel_five.append(data[4])
        self.channel_six.append(data[5])
        self.channel_seven.append(data[6])
        self.channel_eight.append(data[7])
        self.channel_nine.append(data[8])
        self.channel_ten.append(data[9])
        self.channel_eleven.append(data[10])
        self.channel_twelve.append(data[11])
        self.channel_thirteen.append(data[12])
        self.channel_fourteen.append(data[13])
        self.channel_fifteen.append(data[14])
        self.channel_sixteen.append(data[15])
        self.time.append(time)